"""empty message

Revision ID: 882277943529
Revises: ca2a84c2a8c8
Create Date: 2022-11-14 21:34:05.338500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882277943529'
down_revision = 'ca2a84c2a8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
